analytics: {}
color:
  brandColors:
    - '#010200'
    - '#FBFBFB'
    - '#94AAB7'
    - '#C3D2D5'
    - '#647994'
  brandStrength: 0.658305
  lightness: 0.768049
  rhythmicContrast: 0.420393
  saturation: 0.605674
cta: {}
layout_spectrum: 0.352796
name: Love is where you are
opengraph: {}
purpose: {}
typography_spectrum: 0.115174621327782
